name:                anki-md
version:             0.1.0.0

dependencies:
- base
- containers
- filepath
- megaparsec
- pandoc
- pretty-simple
- text

library:
  source-dirs: src

executables:
  anki-md-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - anki-md

tests:
  anki-md-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - anki-md
    - hspec
